### ISSUE TITLE
Discretization is only approximative to first order in their code.

### ISSUE THREAD

**Issue by kpoeppel** [srush/annotated-mamba#4]
Note that in the original repo [^1], they only do the discretization up to first order Taylor approximation of the exponential [^2]. 
$$\bar{b} = \frac{ \( \exp \( \bar{a} \) - 1 \) \Delta b }{\bar{a}} \approx \Delta b ( 1 + \mathcal{O} \( (\Delta a) \) )$$

[^1] https://github.com/state-spaces/mamba/
[^2] https://github.com/state-spaces/mamba/blob/009bec5ee37f586844a3fc89c040a9c1a9d8badf/mamba_ssm/modules/mamba_simple.py#L239

**Comment by srush** [comment]
Thanks! meant to check this.

**Comment by srush** [comment]
For your first line, there still should be an exp right?

**Comment by kpoeppel** [comment]
Yes, of course. I'm sorry for the mistake, error is fixed.
